<?php

namespace Marando\Units;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-22 at 23:51:35.
 */
class PressureTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\Units\Pressure::Pa
   */
  public function testPa() {
    $p = Pressure::Pa(100);

    $this->assertEquals(100, $p->Pa, 'Pa', 1e-10);
    $this->assertEquals(0.0295333727, $p->inHg, 'inHg', 1e-10);
    $this->assertEquals(1, $p->mbar, 'mbar', 1e-10);
  }

  /**
   * @covers Marando\Units\Pressure::mbar
   */
  public function testMbar() {
    $p = Pressure::mbar(1000);

    $this->assertEquals(100000, $p->Pa, 'Pa', 1e-10);
    $this->assertEquals(29.5333727, $p->inHg, 'inHg', 1e-7);
    $this->assertEquals(1000, $p->mbar, 'mbar', 1e-10);
  }

  /**
   * @covers Marando\Units\Pressure::inHg
   */
  public function testInHg() {
    $p = Pressure::inHg(30.1);

    $this->assertEquals(101918.6, $p->Pa, 'Pa', 1e-10);
    $this->assertEquals(30.1, $p->inHg, 'inHg', 1e-10);
    $this->assertEquals(1019.186, $p->mbar, 'mbar', 1e-10);
  }

}
