<?php

namespace Marando\Units;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-16 at 02:32:15.
 */
class TimeTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\Units\Time::fromSeconds
   */
  public function testFromSeconds() {
    $this->assertEquals(182, Time::sec(182)->sec);
  }

  /**
   * @covers Marando\Units\Time::fromMinutes
   */
  public function testFromMinutes() {
    $this->assertEquals(182, Time::min(182)->min);
  }

  /**
   * @covers Marando\Units\Time::fromHours
   */
  public function testFromHours() {
    $this->assertEquals(182, Time::hours(182)->hours);
  }

  /**
   * @covers Marando\Units\Time::fromDays
   */
  public function testFromDays() {
    $this->assertEquals(12, Time::days(0.5)->hours);
  }

  /**
   * @covers Marando\Units\Time::subtract
   */
  public function testSubtract() {
    $t1 = Time::hours(4);
    $t2 = Time::sec(60);

    $this->assertEquals(14340, $t1->subtract($t2)->sec);
  }

  /**
   * @covers Marando\Units\Time::add
   */
  public function testAdd() {
    $t1 = Time::hours(4);
    $t2 = Time::sec(60);

    $this->assertEquals(14460, $t1->add($t2)->sec);
  }

  /**
   * @covers Marando\Units\Time::toAngle
   */
  public function testToAngle() {
    $this->assertEquals(180, time::days(0.5)->toAngle()->deg);
  }

  /**
   * @covers Marando\Units\Time::hms
   */
  public function testHMS() {
    $tests = [
        [-7, 47, 27, -28047],
        [15, 10, 45, 54645],
        [-15, 10, 45, -54645]
    ];

    foreach ($tests as $t)
      $this->assertEquals($t[3], Time::hms($t[0], $t[1], $t[2])->sec);
  }

}
