<?php

namespace Marando\Units;

use \Marando\Units\Time;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-16 at 02:32:15.
 */
class TimeTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\Units\Time::fromSeconds
   */
  public function testFromSeconds() {
    $this->assertEquals(182, Time::fromSeconds(182)->seconds);
  }

  /**
   * @covers Marando\Units\Time::fromMinutes
   * @todo   Implement testFromMinutes().
   */
  public function testFromMinutes() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\Units\Time::fromHours
   * @todo   Implement testFromHours().
   */
  public function testFromHours() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\Units\Time::fromDayFrac
   * @todo   Implement testFromDayFrac().
   */
  public function testFromDayFrac() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\Units\Time::subtract
   * @todo   Implement testSubtract().
   */
  public function testSubtract() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\Units\Time::add
   * @todo   Implement testAdd().
   */
  public function testAdd() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\Units\Time::toAngle
   * @todo   Implement testToAngle().
   */
  public function testToAngle() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
